### ISSUE TITLE
Bad padding error

### ISSUE THREAD

**Issue by tscao** [Benjamin-Loison/GetSamsungEmailPassword#1]
Hey, thanks for the great project and sorry for digging this out.

I have tried your code on a Samsung A510F from 2016 with Android 7.0 and Email version 4.2.79.0. I have retrieved the encrypted password as well as the passcode. It returns a padding error

```
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2168)
	at Main.main(Main.java:23)
```

Would you have any idea what causes this? I have read a bit on it and it seems that besides a padding issue, specifying the wrong encryption algorithm or a bad key (passcode) can also cause this error.

EDIT: I added the actual error printout and the Email app version.

**Comment by tscao** [comment]
I am starting to wonder if, since the Email version you based your solution is more recent, the string I find in files/tmpSetupData might actually be something else than a passcode for a key spec.

**Comment by tscao** [comment]
Ok, turns out I needed to decode the string I found in files/tmpSetupData with the method from https://github.com/lovasoa/samsung-email-password-decrypt, and use the resulting as PASSCODE in your code.

**Comment by tscao** [comment]
Ok, turns out I needed to decode the string I found in files/tmpSetupData with the method from https://github.com/lovasoa/samsung-email-password-decrypt, and use the resulting as PASSCODE in your code.

**Comment by Benjamin-Loison** [comment]
Glad to hear that you solved your issue.

For referencing concerning

> I am starting to wonder if, since the Email version you based your solution is more recent

See https://github.com/Benjamin-Loison/GetSamsungEmailPassword/blob/5e265db2a297ded13c2f3aae1e8835aab09c2c7f/README.md?plain=1#L13-L17
